# Generated by Django 5.0.3 on 2024-03-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_changes', models.IntegerField()),
                ('billing_every_days', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('date_status', models.DateTimeField()),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('next_cycle', models.DateField()),
                ('subscriber_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
