# Generated by Django 5.0.3 on 2024-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_id',
            field=models.CharField(max_length=100),
        ),
    ]
